name: memcached_benchmark

on:
  push:
    branches: [main, ci]
    paths:
      - tools/memcached_benchmark/**
  pull_request:
    branches: [main]
    paths:
      - tools/memcached_benchmark/**

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    if: github.repository == 'rex-rs/rex'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tools/memcached_benchmark

    steps:
      - uses: actions/checkout@v4

      # Install Ubuntu dependencies
      - name: Install Ubuntu dependencies
        run: |
          sudo apt-get install -y pkg-config libzstd-dev mold binutils memcached
          sudo systemctl stop memcached
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 19 all
          sudo update-alternatives --verbose --install /usr/bin/clang clang /usr/bin/clang-19 10000 \
            --slave /usr/bin/lld lld /usr/bin/lld-19 \
            --slave /usr/bin/ld.lld ld.lld /usr/bin/ld.lld-19

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
          toolchain: 1.85.0
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
        with:
          manifest-path: ./tools/memcached_benchmark/Cargo.toml
      - name: Build
        run: RUSTFLAGS='-Ctarget-cpu=native -Clinker-plugin-lto -Clink-arg=-flto=thin -Clink-arg=-fuse-ld=lld -Clink-arg=-Wl,-O1 -Clink-arg=-Wl,--as-needed' cargo build -vvv
      - name: Run tests with debug build
        run: RUSTFLAGS='-Ctarget-cpu=native -Clinker-plugin-lto -Clink-arg=-flto=thin -Clink-arg=-fuse-ld=lld -Clink-arg=-Wl,-O1 -Clink-arg=-Wl,--as-needed' cargo test --verbose
      - name: Run tests with release build
        run: RUSTFLAGS='-Ctarget-cpu=native -Clinker-plugin-lto -Clink-arg=-flto=thin -Clink-arg=-fuse-ld=lld -Clink-arg=-Wl,-O1 -Clink-arg=-Wl,--as-needed' cargo test -r --verbose
